import type { Locale } from "@/i18n/routing";

export const adminCopy = {
  en: {
    admin: "Portfolio admin",
    projects: "Projects",
    newProject: "New project",
    signOut: "Sign out",
    signIn: "Sign in",
    signInIntro: "Use the owner account created with the Better Auth CLI.",
    email: "Email",
    password: "Password",
    github: "Continue with GitHub",
    notConfigured: "Backend setup is not complete.",
    notConfiguredBody:
      "Add every backend variable from .env.example, run the migration, and create the first admin account.",
    search: "Search projects",
    empty: "No projects yet. Create the first one when you are ready.",
    edit: "Edit",
    archive: "Archive",
    restore: "Restore",
    delete: "Delete permanently",
    save: "Save project",
    saving: "Saving…",
    saved: "Project saved",
    details: "Project details",
    content: "Content",
    media: "Cover image",
    upload: "Upload image",
    uploadHint: "JPEG, PNG, WebP or AVIF, up to 5 MB.",
    published: "Published",
    draft: "Draft",
    archived: "Archived",
    all: "All",
    confirmDelete: "Type the project slug to confirm permanent deletion.",
    compact: "Compact table",
  },
  th: {
    admin: "จัดการ Portfolio",
    projects: "ผลงาน",
    newProject: "เพิ่มผลงาน",
    signOut: "ออกจากระบบ",
    signIn: "เข้าสู่ระบบ",
    signInIntro: "ใช้บัญชีเจ้าของเว็บที่สร้างผ่าน Better Auth CLI",
    email: "อีเมล",
    password: "รหัสผ่าน",
    github: "เข้าสู่ระบบด้วย GitHub",
    notConfigured: "ยังตั้งค่าระบบหลังบ้านไม่ครบ",
    notConfiguredBody:
      "ใส่ตัวแปร backend จาก .env.example ให้ครบ รัน migration และสร้างบัญชี admin คนแรก",
    search: "ค้นหาผลงาน",
    empty: "ยังไม่มีผลงาน คุณสามารถสร้างชิ้นแรกได้เมื่อพร้อม",
    edit: "แก้ไข",
    archive: "เก็บเข้าคลัง",
    restore: "นำกลับมา",
    delete: "ลบถาวร",
    save: "บันทึกผลงาน",
    saving: "กำลังบันทึก…",
    saved: "บันทึกแล้ว",
    details: "ข้อมูลผลงาน",
    content: "เนื้อหา",
    media: "ภาพหน้าปก",
    upload: "อัปโหลดรูป",
    uploadHint: "JPEG, PNG, WebP หรือ AVIF ขนาดไม่เกิน 5 MB",
    published: "เผยแพร่แล้ว",
    draft: "ฉบับร่าง",
    archived: "เก็บแล้ว",
    all: "ทั้งหมด",
    confirmDelete: "พิมพ์ slug ของผลงานเพื่อยืนยันการลบถาวร",
    compact: "ตารางแบบกระชับ",
  },
} satisfies Record<Locale, Record<string, string>>;
